# Generated by Django 4.1 on 2023-10-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug_link',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
