# Generated by Django 4.1 on 2023-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_slug_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug_link',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
