# Generated by Django 4.1 on 2023-10-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_books_author_name_author_patronymic_and_more'),
        ('book', '0005_alter_book_slug_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorof', to='author.author'),
        ),
    ]
